---

- name: upload Enable File Auditing script
  win_template:
    src: EnableFileAudit.ps1.j2
    dest: "{{ win_temp_dir }}\\EnableFileAudit.ps1"

- name: Enable File auditing for selected paths
  win_shell: "Powershell -Exec Bypass -File \"{{ win_temp_dir }}\\EnableFileAudit.ps1\" \"{{ item }}\""
  with_items: "{{ win_audit_filepaths }}"
  register: setacl_results
- debug: var=setacl_results
